language: python
dist: xenial
python:
  - 3.6
  - 3.7
  - 3.8
  - 3.9
install:
  - pip3 install pylint
  - pip3 install -r requirements.txt
  - pip3 install -r model/requirements.txt
script:
  - pylint -d R0913 pea_simulator.py
  - pylint model/draw.py
  - pylint -d R0912 -d R0914  model/train.py
